name: Publish

on:
    push:
        tags:
            - v*

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"

            - name: Install dependencies
              run: npm install

            - name: Build package
              run: npm run build

            - name: Publish to npm
              run: |
                  if [[ ${{ github.ref }} == *"alpha"* ]]; then
                    npm publish --tag alpha
                  else
                    npm publish
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
