name: Node.js CI

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "test/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run eslint

            - name: Run tests
              run: npm run test
